### ISSUE TITLE
package.json没有esno！

### ISSUE THREAD

**Issue by thahao** [PHSix/kg#1]
![image](https://github.com/PHSix/kg/assets/63403724/d00b73eb-3bc9-4680-ab4a-3f2f92db1be2)

提示没有安装esno

package.json中没有添加esno的依赖，建议添加

**Comment by PHSix** [comment]
> ![image](https://user-images.githubusercontent.com/63403724/248497772-d00b73eb-3bc9-4680-ab4a-3f2f92db1be2.png)
> 
> 提示没有安装esno
> 
> package.json中没有添加esno的依赖，建议添加

已添加 2c85b23d3559e72f88234e3ec36d4856a1f69144
